list p=18f4520
#include <p18f4520.inc>
CONFIG OSC=HS, PWRT=ON, WDT=OFF, LVP=OFF,PBADEN=OFF
#define duty_44 B'01000100'
#define duty_42 B'01000001'
#define duty_40 B'00111110'
#define duty_38 B'00111010'
#define duty_36 B'00110111'
#define duty_34 B'00110100'
#define duty_32 B'00110001'
COUNT_R equ 0x30
COUNT_L equ 0x31
COUNT_C equ 0x32

org 0x00
    GOTO INITIAL

org 0x40
INITIAL:
    CALL INIT_CCP
    CALL INITIAL_2
    SETF TRISD
    CLRF TRISB
    GOTO LOOP

LOOP:
    CLRF COUNT_R
    CLRF COUNT_L
    CLRF COUNT_C
    BTFSC PORTD,7
    INCF COUNT_R
    BTFSC PORTD,6
    INCF COUNT_R
    BTFSC PORTD,5
    INCF COUNT_R
    BTFSC PORTD,4
    INCF COUNT_R

    BTFSC PORTD,3
    INCF COUNT_L
    BTFSC PORTD,2
    INCF COUNT_L
    BTFSC PORTD,1
    INCF COUNT_L
    BTFSC PORTD,0
    INCF COUNT_L

JUDGE_1:
    MOVF COUNT_R,0
    SUBWF COUNT_L,0
    BTFSC STATUS,2
    GOTO SPEED_ZERO
    BTFSC STATUS,4
    GOTO NEGATIVE
    GOTO POSITIVE

SPEED_ZERO:
    MOVLW B'0000000'
    MOVWF CCPR1L
    MOVWF CCPR2L
    GOTO LOOP
POSITIVE:
    MOVLW duty_40
    MOVWF CCPR1L
    MOVLW duty_44
    MOVWF CCPR2L
    GOTO LOOP

NEGATIVE:
    MOVLW duty_36
    MOVWF CCPR1L
    MOVLW duty_32
    MOVWF CCPR2L
    GOTO LOOP

INIT_CCP:
    MOVLW 0x9B
    MOVWF PR2
    BCF TRISC,2
    BCF TRISB,3
    MOVLW B'00001100'
    MOVWF CCP1CON
    MOVWF CCP2CON
    MOVLW B'00000101'
    MOVWF T2CON
    RETURN

INITIAL_2:
    CLRF COUNT_C
    CLRF COUNT_R
    CLRF COUNT_L
    RETURN

FORWARD:
    BCF LATB,4
    BSF LATB,5
    BCF LATB,6
    BSF LATB,7
    RETURN
BACKWARD:
    BSF LATB,4
    BCF LATB,5
    BSF LATB,6
    BCF LATB,7
    RETURN
SELF_CW:
    BCF LATB,4
    BSF LATB,5
    BSF LATB,6
    BCF LATB,7
    RETURN
SELF_CCW:
    BSF LATB,4
    BCF LATB,5
    BCF LATB,6
    BSF LATB,7
    RETURN
END