list p=18f4520
#include <p18f4520.inc>
CONFIG OSC=HS, PWRT=ON, WDT=OFF, LVP=OFF, PBADEN=OFF
    
VAL_ONE  equ .1
VAL_TMR1 equ .2048
FRE_R    equ 0x30
FRE_G    equ 0x31
FRE_B    equ 0x32
R_FLAG   equ 0x33
G_FLAG   equ 0x34
B_FLAG   equ 0x35

org 0x00
  GOTO INITIAL
;-------------high priority interrupt program----------
org 0x08
  BCF PIR1,TMR1IF
  GOTO JUDGE_RGB
;----------------Initial program start-----------------
org 0x40
INITIAL:
  CALL INITIAL_2
  CALL INITIAL_TMR0
  CALL INITIAL_TMR1
  GOTO MAIN 
;---------------------Main program----------------------
MAIN:
  GOTO MAIN
;------------------Subroutine (interrrupt)-------------
JUDGE_RGB:
INT_R:
  MOVLW B'00000000'
  CPFSEQ R_FLAG
  GOTO INT_G
  GOTO INT_RR
INT_G:
  MOVLW B'00000000'
  CPFSEQ G_FLAG
  GOTO INT_B
  GOTO INT_GG
INT_B:
  MOVLW B'00000000'
  CPFSEQ B_FLAG
  GOTO INT_0
  GOTO INT_BB
INT_0:
  NOP 
  RETFIE

INT_RR:
  MOVF TMR0L,0
  MOVWF FRE_R
  MOVLW (.65536-VAL_TMR1)/.256
  MOVWF TMR1H
  MOVLW (.65536-VAL_TMR1)%.256
  MOVWF TMR1L
  CLRF TMR0L
  MOVLW VAL_ONE
  MOVWF R_FLAG
  CALL INITIAL_G
  RETFIE 
INT_GG:
  MOVF TMR0L,0
  MOVWF FRE_G
  MOVLW (.65536-VAL_TMR1)/.256
  MOVWF TMR1H
  MOVLW (.65536-VAL_TMR1)%.256
  MOVWF TMR1L
  CLRF TMR0L
  MOVLW VAL_ONE
  MOVWF G_FLAG
  CALL INITIAL_B
  RETFIE 
INT_BB:
  MOVF TMR0L,0
  MOVWF FRE_B
  MOVLW (.65536-VAL_TMR1)/.256
  MOVWF TMR1H
  MOVLW (.65536-VAL_TMR1)%.256
  MOVWF TMR1L
  CLRF TMR0L
  MOVLW VAL_ONE
  MOVWF B_FLAG
  CALL INITIAL_R
  CLRF R_FLAG 
  CLRF G_FLAG 
  CLRF B_FLAG   
  GOTO JUDGE_RGB_2
JUDGE_RGB_2:
  MOVLW B'00110111'
  CPFSGT FRE_R
  GOTO INTT_0
  MOVLW B'01010101'
  CPFSLT FRE_R  
  GOTO INTT_0
  MOVLW B'00010100'
  CPFSGT FRE_G
  GOTO INTT_0
  MOVLW B'00110010'
  CPFSLT FRE_G  
  GOTO INTT_0
  MOVLW B'01011111'
  CPFSGT FRE_B
  GOTO INTT_0
  MOVLW B'10001100'
  CPFSLT FRE_B  
  GOTO INTT_0
  GOTO JUDGE_RGB_3
INTT_0:
  BCF LATA,0
  BCF LATD,7
  NOP 
  RETFIE
JUDGE_RGB_3:
  BTFSC PORTB,1
  GOTO RED_POINT
  GOTO INTT_0
RED_POINT:
  BSF LATA,0
  BSF LATD,7
  NOP 
  NOP
  NOP
  NOP
  BCF LATA,0
  RETFIE  
;--------------------Channel of RGB-------------------- 
INITIAL_R:
  BCF LATD,2
  BCF LATD,3
  RETURN
INITIAL_G:
  BSF LATD,2
  BSF LATD,3
  RETURN
INITIAL_B:
  BCF LATD,2
  BSF LATD,3
  RETURN
;--------------------Initial Setting--------------------
INITIAL_2:
  BCF TRISA,0 
  BSF TRISA,4
  BSF TRISB,1 
  BCF TRISD,0
  BCF TRISD,1
  BCF TRISD,2
  BCF TRISD,3 
  BCF TRISD,7 
  BCF LATA,0
  BCF LATB,0
  BCF LATD,0
  BSF LATD,1
  BCF LATD,7
  CLRF R_FLAG 
  CLRF G_FLAG 
  CLRF B_FLAG   
  CALL INITIAL_R
  RETURN
INITIAL_TMR0:
  MOVLW B'11101000'
  MOVWF T0CON
  CLRF TMR0L 
  RETURN
INITIAL_TMR1:
  MOVLW B'10001111'
  MOVWF T1CON
  MOVLW (.65536-VAL_TMR1)/.256
  MOVWF TMR1H
  MOVLW (.65536-VAL_TMR1)%.256
  MOVWF TMR1L
  BSF RCON,IPEN
  BSF INTCON,GIEH
  BSF IPR1,TMR1IP
  BCF PIR1,TMR1IF
  BSF PIE1,TMR1IE
  RETURN
;---------------------Program End----------------------- 
END

